name: Update OWASP dependency checks
pool:
  vmImage: 'Ubuntu 16.04'
variables:
  serviceConnection: azurerm-prod
  keyvaultName: infra-vault-prod
steps:
  - task: AzureKeyVault@1
    displayName: 'Get secrets from Keyvault'
    inputs:
      azureSubscription: ${{ variables.serviceConnection }}
      keyVaultName: ${{ variables.keyvaultName }}
      secretsFilter: 'OWASPDb-Password,OWASPDb-Account'

  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      options: "-DfailBuild=true -DcveValidForHours=24 -Danalyzer.central.enabled=false -Ddata.driver='com.microsoft.sqlserver.jdbc.SQLServerDriver' -Ddata.connectionString='jdbc:sqlserver://owaspdependencycheck.database.windows.net:1433;database=owaspdependencycheck;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;' -Ddata.username='$(OWASPDb-Account)' -Ddata.password=tester --d"
      tasks: 'dependencyCheckUpdate'